# Generated by Django 5.2 on 2026-02-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('OFFICIAL_RECEIPT', 'Official Receipt'), ('SALES_INVOICE', 'Sales Invoice')], max_length=20)),
                ('serial_number', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vatable_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat_exempt_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('zero_rated_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('non_vat_disclaimer', models.TextField(blank=True, default='THIS DOCUMENT IS NOT VALID FOR CLAIM OF INPUT TAX.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='printing.printeraccreditation')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounts.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='businesses.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.receipt')),
            ],
        ),
    ]
