# Generated by Django 5.2 on 2026-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_to_print_number', models.CharField(max_length=100)),
                ('atp_issue_date', models.DateField()),
                ('bir_permit_number', models.CharField(max_length=100)),
                ('printer_name', models.CharField(max_length=255)),
                ('printer_address', models.TextField()),
                ('printer_tin', models.CharField(max_length=15)),
                ('serial_start', models.CharField(max_length=50)),
                ('serial_end', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
