# Generated by Django 5.2 on 2026-02-25 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('tin', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='TIN must be in format 000-000-000-000', regex='^\\d{3}-\\d{3}-\\d{3}-\\d{3}$')])),
                ('branch_code', models.CharField(blank=True, max_length=10, null=True)),
                ('vat_status', models.CharField(choices=[('VAT', 'VAT Registered'), ('NON_VAT', 'Non-VAT Registered')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_registered_books', models.BooleanField(default=False)),
                ('has_registered_pos', models.BooleanField(default=False)),
                ('has_cas_permit', models.BooleanField(default=False)),
                ('cas_permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('printed_by_accredited_printer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='businesses.seller')),
            ],
        ),
    ]
